<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <meta charset="utf-8">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
    <!--[if mso]>
    <noscript>
        <xml>
            <o:OfficeDocumentSettings xmlns:o="urn:schemas-microsoft-com:office:office">
                <o:PixelsPerInch>96</o:PixelsPerInch>
            </o:OfficeDocumentSettings>
        </xml>
    </noscript>
    <style>
        td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
    </style>
    <![endif]-->

    <style>/* Your custom CSS resets for email */
        /*
         * Here is where you can add your global email CSS resets.
         *
         * We use a custom, email-specific CSS reset, instead
         * of Tailwind's web-optimized base.
        */
        body{
            margin: 0;
            width: 100%;
            padding: 0;
            word-break: break-word;
            -webkit-font-smoothing: antialiased;
        }
        img{
            max-width: 100%;
            vertical-align: middle;
            line-height: 100%;
            border: 0;
        }
        /* Tailwind components that are generated by plugins */
        @tailwind components;
        /**
         * @import here any custom CSS components - that is, classes that
         * you'd want loaded before the Tailwind utilities, so the
         * utilities can still override them.
        */
        /* Tailwind utility classes */
        @tailwind utilities;
        /* Your custom utility classes */
        /*
         * Here is where you can define your custom utility classes.
         *
         * We wrap them in the `utilities` @layer directive, so
         * that Tailwind moves them to the correct location.
         *
         * More info:
         * https://tailwindcss.com/docs/functions-and-directives#layer
        */
        .m-0{
            margin: 0 !important;
        }
        .mx-auto{
            margin-left: auto !important;
            margin-right: auto !important;
        }
        .my-32{
            margin-top: 32px !important;
            margin-bottom: 32px !important;
        }
        .mb-16{
            margin-bottom: 16px !important;
        }
        .mb-4{
            margin-bottom: 4px !important;
        }
        .mb-24{
            margin-bottom: 24px !important;
        }
        .block{
            display: block !important;
        }
        .inline-block{
            display: inline-block !important;
        }
        .flex{
            display: flex !important;
        }
        .table{
            display: table !important;
        }
        .hidden{
            display: none !important;
        }
        .h-screen{
            height: 100vh !important;
        }
        .h-\[200px\]{
            height: 200px !important;
        }
        .h-full{
            height: 100% !important;
        }
        .h-\[100px\]{
            height: 100px !important;
        }
        .h-32{
            height: 32px !important;
        }
        .h-64{
            height: 64px !important;
        }
        .h-px{
            height: 1px !important;
        }
        .h-48{
            height: 48px !important;
        }
        .w-5\/6{
            width: 83.333333% !important;
        }
        .w-\[200px\]{
            width: 200px !important;
        }
        .w-full{
            width: 100% !important;
        }
        .w-600{
            width: 600px !important;
        }
        .w-48{
            width: 48px !important;
        }
        .w-1\/2{
            width: 50% !important;
        }
        .max-w-full{
            max-width: 100% !important;
        }
        .max-w-\[800px\]{
            max-width: 800px !important;
        }
        .flex-1{
            flex: 1 1 0% !important;
        }
        .cursor-default{
            cursor: default !important;
        }
        .flex-col{
            flex-direction: column !important;
        }
        .items-center{
            align-items: center !important;
        }
        .justify-center{
            justify-content: center !important;
        }
        .justify-between{
            justify-content: space-between !important;
        }
        .rounded-\[96px\]{
            border-radius: 96px !important;
        }
        .rounded{
            border-radius: 4px !important;
        }
        .border{
            border-width: 1px !important;
        }
        .bg-black{
            background-color: #000000 !important;
        }
        .bg-white{
            background-color: #ffffff !important;
        }
        .bg-\[\#edeeef\]{
            background-color: #edeeef !important;
        }
        .bg-gray-100{
            background-color: #f3f4f6 !important;
        }
        .bg-indigo-800{
            background-color: #3730a3 !important;
        }
        .bg-gray-300{
            background-color: #d1d5db !important;
        }
        .bg-blue-500{
            background-color: #3b82f6 !important;
        }
        .bg-gray-200{
            background-color: #e5e7eb !important;
        }
        .bg-contain{
            background-size: contain !important;
        }
        .bg-cover{
            background-size: cover !important;
        }
        .bg-top{
            background-position: top !important;
        }
        .bg-no-repeat{
            background-repeat: no-repeat !important;
        }
        .p-0{
            padding: 0 !important;
        }
        .p-48{
            padding: 48px !important;
        }
        .p-24{
            padding: 24px !important;
        }
        .py-24{
            padding-top: 24px !important;
            padding-bottom: 24px !important;
        }
        .px-12{
            padding-left: 12px !important;
            padding-right: 12px !important;
        }
        .py-16{
            padding-top: 16px !important;
            padding-bottom: 16px !important;
        }
        .px-24{
            padding-left: 24px !important;
            padding-right: 24px !important;
        }
        .px-48{
            padding-left: 48px !important;
            padding-right: 48px !important;
        }
        .py-32{
            padding-top: 32px !important;
            padding-bottom: 32px !important;
        }
        .pb-32{
            padding-bottom: 32px !important;
        }
        .pr-16{
            padding-right: 16px !important;
        }
        .pl-16{
            padding-left: 16px !important;
        }
        .text-left{
            text-align: left !important;
        }
        .text-center{
            text-align: center !important;
        }
        .font-sans{
            font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important;
        }
        .text-4xl{
            font-size: 36px !important;
        }
        .text-lg{
            font-size: 18px !important;
        }
        .text-base{
            font-size: 16px !important;
        }
        .text-sm{
            font-size: 14px !important;
        }
        .text-2xl{
            font-size: 24px !important;
        }
        .text-xl{
            font-size: 20px !important;
        }
        .text-xs{
            font-size: 12px !important;
        }
        .font-bold{
            font-weight: 700 !important;
        }
        .font-semibold{
            font-weight: 600 !important;
        }
        .uppercase{
            text-transform: uppercase !important;
        }
        .italic{
            font-style: italic !important;
        }
        .leading-full{
            line-height: 100% !important;
        }
        .leading-64{
            line-height: 64px !important;
        }
        .leading-24{
            line-height: 24px !important;
        }
        .leading-px{
            line-height: 1px !important;
        }
        .text-white{
            color: #ffffff !important;
        }
        .text-gray-500{
            color: #6b7280 !important;
        }
        .text-gray-800{
            color: #1f2937 !important;
        }
        .text-blue-500{
            color: #3b82f6 !important;
        }
        .text-black{
            color: #000000 !important;
        }
        .text-gray-600{
            color: #4b5563 !important;
        }
        .underline{
            text-decoration: underline !important;
        }
        .no-underline{
            text-decoration: none !important;
        }
        .shadow-lg{
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05) !important;
        }
        .mso-leading-exactly {
            mso-line-height-rule: exactly !important;
        }
        .hover\:bg-indigo-700:hover{
            background-color: #4338ca !important;
        }
        .hover\:bg-blue-600:hover{
            background-color: #2563eb !important;
        }
        .hover\:text-blue-400:hover{
            color: #60a5fa !important;
        }
        .hover\:underline:hover{
            text-decoration: underline !important;
        }
        .hover\:no-underline:hover{
            text-decoration: none !important;
        }
        @media (max-width: 600px){
            .sm\:inline-block{
                display: inline-block !important;
            }
            .sm\:h-32{
                height: 32px !important;
            }
            .sm\:w-full{
                width: 100% !important;
            }
            .sm\:w-16{
                width: 16px !important;
            }
            .sm\:px-16{
                padding-left: 16px !important;
                padding-right: 16px !important;
            }
            .sm\:py-32{
                padding-top: 32px !important;
                padding-bottom: 32px !important;
            }
            .sm\:px-24{
                padding-left: 24px !important;
                padding-right: 24px !important;
            }
            .sm\:px-0{
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            .sm\:pb-32{
                padding-bottom: 32px !important;
            }
            .sm\:leading-40{
                line-height: 40px !important;
            }
            .sm\:leading-32{
                line-height: 32px !important;
            }
        }</style>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    <style>
        @font-face {
            font-family: 'Lato';
            font-style: normal;
            src: url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');

        }
        .font-lato{
            font-family: 'Lato';
        }
    </style>
</head>
<body class="undefined">
<div role="article" aria-roledescription="email" aria-label="" lang="en">

    <div class="bg-black flex flex-col h-screen">
        <header class="h-[200px] bg-black text-white py-24">
            <div class="flex justify-between w-5/6 mx-auto h-full items-center">
                <div><img src="{{asset('/images/nadil.png')}}" alt=""></div>
                <div class="bg-contain bg-no-repeat w-[200px] h-full" style="background-image: url('{{asset('/images/nadil-cutlery.png')}}');"></div>
            </div>
        </header>
        <main class="flex-1 flex flex-col bg-white rounded-[96px] justify-center items-center ">
            <div class="w-5/6 py-24 px-12 shadow-lg bg-[#edeeef] rounded-[96px] max-w-[800px]">
                <div class="font-lato font-bold text-center uppercase my-32">Hi {{$user->name}}</div>
                <div class="font-lato font-bold text-center uppercase my-32">Welcome to Nadil</div>
                <div class="font-lato font-bold text-center uppercase my-32">Thank you <br>for signing up with us</div>
                <div class="font-lato font-bold text-center uppercase my-32">We cannot wait for your <br> booking experience </div>
            </div>
        </main>
        <footer class="bg-black h-[100px]">
            <div class="flex"></div>
        </footer>
    </div>

</div>
</body>
</html>
